import { Injectable } from '@angular/core';
import { Insta} from '../model/instagram.model';

@Injectable({
  providedIn: 'root',
})
export class InstagramService {
  city: Insta[] = [
    {
      pseudo: 'Abal Utrema',
      titre: 'Paysage Touristique en Chilie',
      date: new Date(),
      description:
        'Un magnifique endroit au large du Chilie pour explorer la beauté de lanature',
      localisation: 'Chilie',
      nbrAime: 97,
      imageUrl: '../assets/paysage_01.jpg',
      nbrAimeCom: 2,
      commentaire: ['li nice na deh  ! ', ],
    },
    {
      pseudo: 'Kakashi Seinsei',
      titre: 'Paysage Touristique Situé au Kenya',
      date: new Date(),
      description: 'Photo prise dans la nature Kenyanne',
      localisation: 'Kenya',
      nbrAime: 36,
      imageUrl: '../assets/paysage_02.jpg',
      nbrAimeCom: 7,
      commentaire: ['très calme '],
    },
    {
      pseudo: 'Luffy',
      titre: 'Paysage Touristique Français',
      date: new Date(),
      description: 'Chaîne de montagnes',
      localisation: 'France',
      nbrAime: 45,
      imageUrl: '../assets/paysage_03.jpg',
      nbrAimeCom: 0,
      commentaire: ['wonderfull '],
    },
    {
      pseudo: 'FatyCoumba',
      titre: 'Paysage Touristique Marocain',
      date: new Date(),
      description: 'Port Touristique au large des côtes marocaines',
      localisation: 'Maroc',
      nbrAime: 87,
      imageUrl: '../assets/paysage_04.jpg',
      nbrAimeCom: 11,
      commentaire: ['wooowwww !'],
    },
    {
      pseudo: 'Mamoudal',
      titre: 'Paysage Touristique Indien',
      date: new Date(),
      description: "Enceinte d'un chateau en Inde",
      localisation: 'Inde',
      nbrAime: 45,
      imageUrl: '../assets/paysage_05.jpg',
      nbrAimeCom: 1,
      commentaire: ['okay on fait la visite '],
    },
    {
      pseudo: 'Nabil_Fekir18',
      titre: 'Paysage Touristique Français',
      date: new Date(),
      description: 'Forêt classée dans la ville Bourgogne',
      localisation: 'Bourgogne',
      nbrAime: 23,
      imageUrl: '../assets/paysage_06.jpg',
      nbrAimeCom: 3,
      commentaire: ['MachaAllah !'],
    },
    {
      pseudo: 'MadaraUchiwa',
      titre: 'Paysage Touristique Canadien',
      date: new Date(),
      description: 'Chute de Niagara',
      localisation: 'Canada',
      nbrAime: 54,
      imageUrl: '../assets/paysage_07.jpg',
      nbrAimeCom: 0,
      commentaire: ['ce site touristique doit etre visité'],
    },
    {
      pseudo: 'Zaraki667',
      titre: 'Paysage Touristique Haïtien',
      date: new Date(),
      description: 'Chaîne de montagnes haïtien',
      localisation: 'Haïti',
      nbrAime: 47,
      imageUrl: '../assets/paysage_08.jpg',
      nbrAimeCom: 0,
      commentaire: ['ce pays est magnifique'],
    },
    {
      pseudo: 'Sakura',
      titre: 'Paysage Touristique Haïtien',
      date: new Date(),
      description: 'Plage balnière',
      localisation: 'Haïti',
      nbrAime: 26,
      imageUrl: '../assets/paysage_09.jpg',
      nbrAimeCom: 0,
      commentaire: ['Lafthiate !!!'],
    },
    {
      pseudo: 'AllMight',
      titre: 'Paysage Touristique Norvègien',
      date: new Date(),
      description: 'Plaine rurale',
      localisation: 'Norvège',
      nbrAime: 47,
      imageUrl: '../assets/paysage_10.jpg',
      nbrAimeCom: 0,
      commentaire: ['MachAllah '],
    },
    {
      pseudo: 'JirenSKrr',
      titre: 'Paysage Touristique Marocain',
      date: new Date(),
      description: "Photo d'un village marocain",
      localisation: 'Maroc',
      nbrAime: 31,
      imageUrl: '../assets/paysage_11.jpg',
      nbrAimeCom: 0,
      commentaire: ['wooowwwwwwwwwww'],
    },
    {
      pseudo: 'Gokou',
      titre: 'Paysage Touristique Indénosien',
      date: new Date(),
      description: 'Place balnière',
      localisation: 'Indonésie',
      nbrAime: 52,
      imageUrl: '../assets/paysage_12.jpg',
      nbrAimeCom: 0,
      commentaire: ['Magnifique'],
    },
    {
      pseudo: 'Naruto',
      titre: 'Paysage Touristique Papouasien',
      date: new Date(),
      description: "Hôtel sur l'océan indien",
      localisation: 'Papouasie Nouvelle Guinée',
      nbrAime: 14,
      imageUrl: '../assets/paysage_13.jpg',
      nbrAimeCom: 0,
      commentaire: ['Félicitations !'],
    },
    {
      pseudo: 'Boruto',
      titre: 'Paysage Touristique Béninois',
      date: new Date(),
      description: 'Cascade',
      localisation: 'Bénin',
      nbrAime: 30,
      imageUrl: '../assets/paysage_14.jpg',
      nbrAimeCom: 0,
      commentaire: ['tu es un génie'],
    },
    {
      pseudo: 'Shine',
      titre: 'Paysage Touristique Grecque',
      date: new Date(),
      description: 'Ville Côtière',
      localisation: 'Grèce',
      nbrAime: 60,
      imageUrl: '../assets/paysage_15.jpg',
      nbrAimeCom: 0,
      commentaire: ['shine like diamond'],
    },
    {
      pseudo: 'Paine77',
      titre: 'Paysage Touristique Autrichien',
      date: new Date(),
      description: "Vue d'un lac",
      localisation: 'Autriche',
      nbrAime: 74,
      imageUrl: '../assets/paysage_16.jpg',
      nbrAimeCom: 2,
      commentaire: ['Wonderfull'],
    },
    {
      pseudo: 'Doflamingo',
      titre: 'Paysage Touristique Serbe',
      date: new Date(),
      description: "Vue aérienne d'une ville Serbe",
      localisation: 'Serbie',
      nbrAime: 25,
      imageUrl: '../assets/paysage_17.jpg',
      nbrAimeCom: 0,
      commentaire: ['la photo est magnifique'],
    },
    {
      pseudo: 'Katakuri',
      titre: 'Paysage Touristique Sud Coréen',
      date: new Date(),
      description: 'Busan, Deuxième plus grande ville',
      localisation: 'Corée du Sud',
      nbrAime: 20,
      imageUrl: '../assets/paysage_18.jpg',
      nbrAimeCom: 0,
      commentaire: ['Magnifique'],
    },
    {
      pseudo: 'Sileymane45',
      titre: 'Paysage Touristique Sud Coréen',
      date: new Date(),
      description: 'Jeonju, Ville situé au sud-ouest de la capitale',
      localisation: 'Corée du Sud',
      nbrAime: 132,
      imageUrl: '../assets/paysage_19.jpg',
      nbrAimeCom: 0,
      commentaire: ['Wonderful'],
    },
    {
      pseudo: 'Abal667',
      titre: 'Paysage Touristique Sud Coréen',
      date: new Date(),
      description: 'Vue du fleuve Han situé à Séoul',
      localisation: 'Corée du Sud',
      nbrAime: 666,
      imageUrl: '../assets/paysage_20.jpg',
      nbrAimeCom: 6,
      commentaire: ['Waww'],
    },
  ];

  getAllSnap() {
    return this.city;
  }
  constructor() {}
}
